export const ADD_NEW_TASK_START = 'ADD_NEW_TASK_START';
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS';
export const ADD_NEW_TASK_FAILURE = 'ADD_NEW_TASK_FAILURE';

export const FETCH_TASK_LIST_START = 'FETCH_TASK_LIST_START';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILURE = 'FETCH_TASK_LIST_FAILURE';

export const SELECT_TASK = 'SELECT_TASK';