export const ADD_NEW_TASK_START = 'ADD_NEW_TASK_START';
export const ADD_NEW_TASK_SUCCESS = 'ADD_NEW_TASK_SUCCESS';
export const ADD_NEW_TASK_FAILURE = 'ADD_NEW_TASK_FAILURE';

export const FETCH_TASK_LIST_START = 'FETCH_TASK_LIST_START';
export const FETCH_TASK_LIST_SUCCESS = 'FETCH_TASK_LIST_SUCCESS';
export const FETCH_TASK_LIST_FAILURE = 'FETCH_TASK_LIST_FAILURE';

export const UPDATE_TASK_START = 'UPDATE_TASK_START';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
export const UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE';
export const RESET_DELETE_TASK = 'RESET_DELETE_TASK';

export const SELECT_TASK = 'SELECT_TASK';
export const RESET_SELECT_TASK = 'RESET_SELECT_TASK';